---
- name: Deploy Docker Image to Container
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: umeshjaware/umesh_pipeline
        tag: latest
        source: pull

    - name: Create & Start Calculator Docker Container
      docker_container:
        name: calculator-using-devops
        image: umeshjaware/umesh_pipeline
        state: started
        tty: yes
        interactive: yes
